### PR TITLE
Update README (remove ContextPreservingExecutor)

### PR DESCRIPTION
**Pull request by steinnes**
Remove outdated references to custom context preserving executor from README.md

This should prevent others from running into any confusing like described in issue #7

### CODE REVIEW

**Comment by steinnes** [comment]
I just switched to sentry (not sure why I keep straying away tbh), noticed that the README was still outdated.

@tomchristie did I miss something?

**Comment by lovelydinosaur** [comment]
I'd have merged this in but there's obv an *unrelated* test failure that's associated with the PR.

**Comment by lovelydinosaur** [comment]
I know this is a docs PR, and obvious correct, but I still kinda need to sort out why the builds currently fail. No doubt a versioning thing that's not properly locked.

**Comment by lovelydinosaur** [comment]
Okay, this is in now - thanks for bumping it to my attention.

**Pull request closed without merging**
